export const AuditAction = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  USER_BOOTSTRAP: 'USER_BOOTSTRAP',
  SESSION_REVOKED: 'SESSION_REVOKED',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  MEDIA_UPLOAD: 'MEDIA_UPLOAD',
  MEDIA_METADATA_UPDATE: 'MEDIA_METADATA_UPDATE',
  MEDIA_ARCHIVE: 'MEDIA_ARCHIVE',
  MEDIA_DELETE: 'MEDIA_DELETE',
  CONTENT_DRAFT_CREATED: 'CONTENT_DRAFT_CREATED',
  CONTENT_DRAFT_UPDATED: 'CONTENT_DRAFT_UPDATED',
  CONTENT_SUBMITTED_REVIEW: 'CONTENT_SUBMITTED_REVIEW',
  CONTENT_RETURNED_TO_DRAFT: 'CONTENT_RETURNED_TO_DRAFT',
  CONTENT_APPROVED: 'CONTENT_APPROVED',
  CONTENT_PUBLISHED: 'CONTENT_PUBLISHED',
  CONTENT_UNPUBLISHED: 'CONTENT_UNPUBLISHED',
  CONTENT_RESTORED: 'CONTENT_RESTORED',
  REDIRECT_CREATED: 'REDIRECT_CREATED',
  REDIRECT_DISABLED: 'REDIRECT_DISABLED',
  REDIRECT_ENABLED: 'REDIRECT_ENABLED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_ENABLED: 'USER_ENABLED',
  USER_ROLES_UPDATED: 'USER_ROLES_UPDATED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  USER_SESSION_REVOKED: 'USER_SESSION_REVOKED',
  USER_ALL_SESSIONS_REVOKED: 'USER_ALL_SESSIONS_REVOKED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction] | string;

export interface AuditEventInput {
  actorId?: string | null;
  actorEmail?: string | null;
  action: AuditActionType;
  entityType?: string | null;
  entityId?: string | null;
  ipAddress?: string | null;
  userAgent?: string | null;
  metadata?: Record<string, unknown>;
}
