import sitemapFn from '../src/app/sitemap.ts';
import { getLegacyRedirect } from '../src/lib/routing/redirects.ts';

console.log('=== SITEMAP VERIFICATION AUDIT ===\n');

const sitemap = typeof sitemapFn === 'function' ? sitemapFn : sitemapFn.default;
const entries = sitemap();
console.log(`Total URLs generated by sitemap.ts: ${entries.length}`);

// 1. Check for duplicates
const urlSet = new Set();
const duplicates = [];
entries.forEach(e => {
  if (urlSet.has(e.url)) {
    duplicates.push(e.url);
  }
  urlSet.add(e.url);
});

console.log(`Unique URLs in sitemap: ${urlSet.size}`);
if (duplicates.length > 0) {
  console.error(`DUPLICATES FOUND (${duplicates.length}):`, duplicates);
} else {
  console.log('[PASS] Zero duplicate URLs in sitemap.');
}

// 2. Check trailing slash on all URLs
let trailingSlashFailures = 0;
entries.forEach(e => {
  if (!e.url.endsWith('/')) {
    console.error(`Missing trailing slash: ${e.url}`);
    trailingSlashFailures++;
  }
});
if (trailingSlashFailures === 0) {
  console.log('[PASS] 100% of sitemap URLs have strict trailing slashes.');
}

// 3. Check for any redirects present in sitemap
const redirectsFound = [];
entries.forEach(e => {
  const urlObj = new URL(e.url);
  const path = urlObj.pathname.replace(/^\/|\/$/g, '');
  if (getLegacyRedirect(path)) {
    redirectsFound.push(e.url);
  }
});
if (redirectsFound.length > 0) {
  console.error(`REDIRECTS FOUND IN SITEMAP (${redirectsFound.length}):`, redirectsFound);
} else {
  console.log('[PASS] Zero redirects present in sitemap (100% canonical indexable).');
}

// 4. Check for API / admin / block paths
let invalidPaths = 0;
entries.forEach(e => {
  if (e.url.includes('/api/') || e.url.includes('/admin/') || e.url.includes('/blocks/')) {
    console.error(`Invalid internal URL in sitemap: ${e.url}`);
    invalidPaths++;
  }
});
if (invalidPaths === 0) {
  console.log('[PASS] Zero internal, API, or UX Block paths in sitemap.');
}

console.log('\n--- FINAL SITEMAP COUNT ---');
console.log(`Authoritative Sitemap URL Count: ${entries.length}`);
